version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: agendadb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d agendadb"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: fastapi_api
    restart: always
    build: ./api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://admin:password123@db:5432/agendadb"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app

  n8n:
    image: n8nio/n8n
    container_name: n8n_automations
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
    depends_on:
      api:
        condition: service_started
      db:
        condition: service_healthy

  chatbot_ui:
    container_name: streamlit_chatbot
    restart: always
    build: ./streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - n8n
    volumes:
      - ./streamlit_app:/app

volumes:
  postgres_data:
  n8n_data: